defaults: &defaults
  redis:
    host: <%= ENV['REDIS_HOST'] || 'localhost' %>
    port: <%= ENV['REDIS_PORT'] || '6379' %>
    password: <%= ENV['REDIS_PASSWORD'] || "" %>

  digest_secret: <%= ENV['DIGEST_SECRET'] || 'da4b0aaec42c8a17183b5c52be5cd3b0' %>
  max_file_content_size: <%= ENV['MAX_FILE_CONTENT_SIZE'] || 31457280 %>
  integrations:
    dropbox:
      client_id: <%= ENV['DROPBOX_CLIENT_ID'] || 'a1lacf0749xcl6p' %>
      client_secret: <%= ENV['DROPBOX_CLIENT_SECRET'] || '6ioipyw0wypiaq3' %>
      ecl_client_id: <%= ENV['DROPBOX_ECL_CLIENT_ID'] || 'z3M3-yxsyg' %>
      ecl_token: <%= ENV['DROPBOX_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6InozTTMteXhzeWciLCJlbWFpbCI6ImFtYXJAZWRjYXN0LmNvbSJ9.JoPRp0MyvVPIHFd8ZCOygoDackUgFO40y5qtKvMxAs0' %>
      source_type_id:  <%= ENV['DROPBOX_SOURCE_TYPE_ID'] || 'abc' %>
    box:
      client_id: <%= ENV['BOX_CLIENT_ID'] || 'iotp53bgk64biyrm8hm8vx5g0paoap5i' %>
      client_secret: <%= ENV['BOX_CLIENT_SECRET'] || 'FukImsYbir9ifPTGdxgZvhh65zviptBN' %>
      ecl_client_id: <%= ENV['BOX_ECL_CLIENT_ID'] || 'Ej4bAsuYiw' %>
      ecl_token: <%= ENV['BOX_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6IkVqNGJBc3VZaXciLCJlbWFpbCI6Im5pbGVzaF9uYXZhbGVAcGVyc2lzdGVudC5jby5pbiJ9.t2Tm0-jlF21kBiNpsRmDbpLUQmp8K5qoWviJqbz0bvg' %>
      source_type_id:  <%= ENV['BOX_SOURCE_TYPE_ID'] || '3974e7a3-b466-40b5-a7db-4748ffc8ff4a' %>
    team_drive:
      client_id: <%= ENV['TEAM_DRIVE_CLIENT_ID'] || 'eks77359dcm819n' %>
      client_secret: <%= ENV['TEAM_DRIVE_CLIENT_SECRET'] || 'bfgz7hc0z7vn6b1' %>
      ecl_client_id: <%= ENV['TEAM_DRIVE_ECL_CLIENT_ID'] || '9fJcx5yqeg' %>
      ecl_token: <%= ENV['TEAM_DRIVE_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6IjlmSmN4NXlxZWciLCJlbWFpbCI6InlvZ2VuZHJhKzMyNDEyQGVkY2FzdC5jb20ifQ.-C9jUXPslVmdtO0zR8Oz7-i0i7PuWVbKkM9Zu1z0fCc' %>
      source_type_id:  <%= ENV['TEAM_DRIVE_SOURCE_TYPE_ID'] || 'xyz' %>
    safari_books_online:
      ecl_client_id: <%= ENV['SAFARI_BOOKS_ONLINE_ECL_CLIENT_ID'] || 'o-m8JtbcSQ' %>
      ecl_token: <%= ENV['SAFARI_BOOKS_ONLINE_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6Im8tbThKdGJjU1EiLCJlbWFpbCI6InBhbGxhdisxQGVkY2FzdC5jb20ifQ.4yURzwX8EPsrdDDu-f5bC2I0PT4lih781MkixduITe8' %>
      source_type_id:  <%= ENV['SAFARI_BOOKS_ONLINE_SOURCE_TYPE_ID'] || 'foo' %>
    linkedin_learning:
      client_id: <%= ENV['LINKEDIN_LEARNING_CLIENT_ID'] || '7828s2gqfyjvp0' %>
      client_secret: <%= ENV['LINKEDIN_LEARNING_CLIENT_SECRET'] || 'F8LpE0oCB7oJ71ia' %>
      ecl_client_id: <%= ENV['LINKEDIN_LEARNING_ECL_CLIENT_ID'] || 'Ej4bAsuYiw' %>
      ecl_token: <%= ENV['LINKEDIN_LEARNING_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6IkVqNGJBc3VZaXciLCJlbWFpbCI6Im5pbGVzaF9uYXZhbGVAcGVyc2lzdGVudC5jby5pbiJ9.t2Tm0-jlF21kBiNpsRmDbpLUQmp8K5qoWviJqbz0bvg' %>
      source_type_id:  <%= ENV['LINKEDIN_LEARNING_SOURCE_TYPE_ID'] || '0a5b5557-a22e-44d7-be50-7996cd8504d6' %>
    sharepoint:
      client_id:  <%= ENV['SHAREPOINT_CLIENT_ID'] || '0138a21b-af37-47ee-9dad-c7f23fb5b2a6' %>
      client_secret: <%= ENV['SHAREPOINT_CLIENT_SECRET'] || 'lyoxNNFAU2651])nhhCA2<(' %>
      ecl_client_id: <%= ENV['SHAREPOINT_ECL_CLIENT_ID']  || "Y96ZRvXXjA" %>
      ecl_token: <%= ENV['SHAREPOINT_ECL_CLIENT_TOKEN'] || "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6Ilk5NlpSdlhYakEiLCJlbWFpbCI6ImRhcnNoYW5fcGF0ZWxAcGVyc2lzdGVudC5jby5pbiJ9.bF638d7ZPiaXTSMZiEb4HgyOEhDN28zS-wXoRDtfa3U" %>
      source_type_id:  <%= ENV['SHAREPOINT_SOURCE_TYPE_ID'] || '1835f385-8e20-4a84-bde4-db8aebc95f8b' %>
development:
  <<: *defaults


test:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults

production:
  <<: *defaults
