defaults: &defaults
  dropbox_client_id:  <%= ENV['DROPBOX_CLIENT_ID'] || 'eks77359dcm819n' %>
  dropbox_client_secret: <%= ENV['DROPBOX_CLIENT_SECRET'] || 'bfgz7hc0z7vn6b1' %>
  dropbox_redirce_uri: 'http://localhost:5000/dropbox/callback'
  google_team_drive_client_id:  <%= ENV['GOOGLE_TEAM_DRIVE_CLIENT_ID'] || 'eks77359dcm819n' %>
  google_team_drive_client_secret: <%= ENV['GOOGLE_TEAM_DRIVE_CLIENT_SECRET'] || 'bfgz7hc0z7vn6b1' %>
  google_team_drive_redirect_uri: 'http://localhost:5000/google_team_drive/callback'
  digest_secret: '34899d721ba319bb99f79847d5146093'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults

production:
  <<: *defaults
