defaults: &defaults
  digest_secret: '34899d721ba319bb99f79847d5146093'
  ecl_app_url: <%= ENV['ECL_APP_URL'] || "http://localhost:3000/api/developer/v1" %>
  dropbox:
    client_id: <%= ENV['DROPBOX_CLIENT_ID'] || 'Dfsn19ehHA' %>
    client_secret: <%= ENV['DROPBOX_CLIENT_SECRET'] || 'Dfsn19ehHA' %> 
    ecl_app_client: <%= ENV['DROPBOX_ECL_CLIENT_ID'] || 'Dfsn19ehHA' %>
    ecl_app_token: <%= ENV['DROPBOX_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6IkRmc24xOWVoSEEifQ.npB8vBKFfUUSi9OCSykqDzzbnPgu1w1u25ZrmiBk1Bo' %>
    redirect_uri: <%= ENV['DROPBOX_REDIRECT_URL'] || 'http://localhost:5000/dropbox/callback' %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults

production:
  <<: *defaults
