defaults: &defaults
  client_id:  <%= ENV['CLIENT_ID'] || 'eks77359dcm819n' %>
  client_secret: <%= ENV['CLIENT_SECRET'] || 'bfgz7hc0z7vn6b1' %>
  redirect_uri: 'http://localhost:5000/dropbox/callback'
  digest_secret: '34899d721ba319bb99f79847d5146093'
  ecl_app_url: <%= ENV['ECL_APP_URL'] || "http://localhost:3000" %>
  ecl_app_client: <%= ENV['ECL_APP_CLIENT']  || "Dfsn19ehHA" %>
  ecl_app_token: <%= ENV['ECL_APP_TOKEN'] || "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWV9.g8N5057cxx3tYKoBxPTppfRmptoYo8hjgPtzqEWyUJk" %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults

production:
  <<: *defaults
