defaults: &defaults
  redis:
    host: <%= ENV['REDIS_HOST'] || 'localhost' %>
    port: <%= ENV['REDIS_PORT'] || '6379' %>
    password: <%= ENV['REDIS_PASSWORD'] || "" %>

  digest_secret: <%= ENV['DIGEST_SECRET'] || 'da4b0aaec42c8a17183b5c52be5cd3b0' %>
  ecl_app_url: <%= ENV['ECL_APP_URL'] || "http://qa.edcast.io/api/developer/v1" %>
  integrations:
    dropbox:
      client_id: <%= ENV['DROPBOX_CLIENT_ID'] || 'a1lacf0749xcl6p' %>
      client_secret: <%= ENV['DROPBOX_CLIENT_SECRET'] || '6ioipyw0wypiaq3' %>
      ecl_client_id: <%= ENV['DROPBOX_ECL_CLIENT_ID'] || 'z3M3-yxsyg' %>
      ecl_token: <%= ENV['DROPBOX_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6InozTTMteXhzeWciLCJlbWFpbCI6ImFtYXJAZWRjYXN0LmNvbSJ9.JoPRp0MyvVPIHFd8ZCOygoDackUgFO40y5qtKvMxAs0' %>
      source_type_id:  <%= ENV['DROPBOX_SOURCE_TYPE_ID'] || 'abc' %>
    team_drive:
      client_id: <%= ENV['TEAM_DRIVE_CLIENT_ID'] || 'eks77359dcm819n' %>
      client_secret: <%= ENV['TEAM_DRIVE_CLIENT_SECRET'] || 'bfgz7hc0z7vn6b1' %>
      ecl_client_id: <%= ENV['TEAM_DRIVE_ECL_CLIENT_ID'] || '9fJcx5yqeg' %>
      ecl_token: <%= ENV['TEAM_DRIVE_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6IjlmSmN4NXlxZWciLCJlbWFpbCI6InlvZ2VuZHJhKzMyNDEyQGVkY2FzdC5jb20ifQ.-C9jUXPslVmdtO0zR8Oz7-i0i7PuWVbKkM9Zu1z0fCc' %>
      source_type_id:  <%= ENV['TEAM_DRIVE_SOURCE_TYPE_ID'] || 'xyz' %>
    safari_books_online:
      ecl_client_id: <%= ENV['SAFARI_BOOKS_ONLINE_ECL_CLIENT_ID'] || 'o-m8JtbcSQ' %>
      ecl_token: <%= ENV['SAFARI_BOOKS_ONLINE_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6Im8tbThKdGJjU1EiLCJlbWFpbCI6InBhbGxhdisxQGVkY2FzdC5jb20ifQ.4yURzwX8EPsrdDDu-f5bC2I0PT4lih781MkixduITe8' %>
      source_type_id:  <%= ENV['SAFARI_BOOKS_ONLINE_SOURCE_TYPE_ID'] || 'foo' %>
    sharepoint:
      client_id:  <%= ENV['SHAREPOINT_CLIENT_ID'] || '0138a21b-af37-47ee-9dad-c7f23fb5b2a6' %>
      client_secret: <%= ENV['SHAREPOINT_CLIENT_SECRET'] || 'lyoxNNFAU2651])nhhCA2<(' %>
      ecl_client_id: <%= ENV['SHAREPOINT_ECL_CLIENT_ID']  || "Y96ZRvXXjA" %>
      ecl_token: <%= ENV['SHAREPOINT_ECL_CLIENT_TOKEN'] || "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6Ilk5NlpSdlhYakEiLCJlbWFpbCI6ImRhcnNoYW5fcGF0ZWxAcGVyc2lzdGVudC5jby5pbiJ9.bF638d7ZPiaXTSMZiEb4HgyOEhDN28zS-wXoRDtfa3U" %>
      source_type_id:  <%= ENV['SHAREPOINT_SOURCE_TYPE_ID'] || 'c36a0d27-05c0-4d36-9c06-8bf38a8be9cc' %>
    kpoint:
      client_id: <%= ENV['KPOINT_CLIENT_ID'] || 'cicd1f44f82f224bb99c15db0a5f99c755' %>
      client_secret: <%= ENV['KPOINT_CLIENT_SECRET'] || 'sk1bddb184792543259e2d377361158ef9' %>
      ecl_client_id: <%= ENV['KPOINT_ECL_CLIENT_ID'] || 'Ej4bAsuYiw' %>
      ecl_token: <%= ENV['KPOINT_ECL_TOKEN'] || 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc19kZXZlbG9wZXIiOnRydWUsImNsaWVudF9pZCI6IkVqNGJBc3VZaXciLCJlbWFpbCI6Im5pbGVzaF9uYXZhbGVAcGVyc2lzdGVudC5jby5pbiJ9.t2Tm0-jlF21kBiNpsRmDbpLUQmp8K5qoWviJqbz0bvg' %>
      request_uri: <%= ENV['KPOINT_REQUEST_URI'] || 'https://videoken.zencite.com' %>
      redirect_uri: <%= ENV['KPOINT_REDIRECT_URL'] || 'http://localhost:3000/kpoint/callback' %>
      source_type_id:  <%= ENV['KPOINT_SOURCE_TYPE_ID'] || 'b64d90c3-7ddb-458c-b057-b0c52c2da05c' %>
      name: "Kpoint"
      source_type_name: "Kpoint"
development:
  <<: *defaults


test:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults

production:
  <<: *defaults
