# Sidekiq Queues
# Three queues will be used for each Integration.
# Naming of queus will be based on integration-name as follows.
# 1. "#{integration_name}"
# 2. "#{integration_name}_ecl_job"
# 3. "#{integration_name}_content_creation_job"

:concurrency: 2
:pidfile: ./sidekiq.pid
:logfile: ./sidekiq.log
qa:
  :concurrency: 3
staging:
  :concurrency: 3
production:
  :concurrency: 5
:queues:
  - [dropbox, 5]
  - [content_item_job, 5]
  - [dropbox_ecl_job, 3]
  - [google_team_drive, 5]
  - [google_team_drive_ecl_job, 3]
  - [safari_books_online_ecl_job, 3]
  - [safari_books_online, 3]
  - [linkedin_learning_ecl_job, 3]
  - [linkedin_learning, 3]
  - [sharepoint, 5]
  - [sharepoint_ecl_job, 3]
  - [sftp, 5]
  - [sftp_ecl_job, 3]
  - [edx_enterprise, 5]
  - [edx_enterprise_ecl_job, 3]
  - [boxr, 5]
  - [boxr_ecl_job, 3]
  - [sharepoint_onprem, 5]
  - [sharepoint_onprem_ecl_job, 3]
  - [google_drive, 5]
  - [google_drive_ecl_job, 3]
  - [nuvepro_ecl_job, 3]
  - [nuvepro, 3]
  - [one_drive, 5]
  - [one_drive_ecl_job, 3]
  - [skill_soft_ecl_job, 3]
  - [skill_soft, 3]
  - [safari_books_online_public_ecl_job, 3]
  - [safari_books_online_public, 3]
  - [cornerstone_ecl_job, 3]
  - [cornerstone, 3]
  